# **PANDAS**

The reason of importing NumPy with Pandas:
- Pandas is built on top of NumPy, and many of the operations and data structures in Pandas rely on NumPy arrays. While you can use Pandas without explicitly importing NumPy, it's common practice to import both because you might need NumPy functions or data types when working with Pandas DataFrames or Series.

In [3]:
import numpy as np

In [4]:
import pandas as pd

In [5]:
#!pip install pandas

***-SERIES***

In [6]:
grades = {"Atil":50, "James": 60, "Lars":30}

In [7]:
pd.Series(grades)

Atil     50
James    60
Lars     30
dtype: int64

In [8]:
names = ["Atil","James","Lars"]
grades = [50,60,30]

In [9]:
pd.Series(names)

0     Atil
1    James
2     Lars
dtype: object

In [10]:
pd.Series(grades)

0    50
1    60
2    30
dtype: int64

In [11]:
pd.Series(names,grades)

50     Atil
60    James
30     Lars
dtype: object

In [12]:
pd.Series(grades,names)

Atil     50
James    60
Lars     30
dtype: int64

In [13]:
pd.Series(data=grades, index=names)

Atil     50
James    60
Lars     30
dtype: int64

In [14]:
#with numpy

In [15]:
numpy_array = np.array([50,40,30,20])

In [16]:
pd.Series(numpy_array)

0    50
1    40
2    30
3    20
dtype: int64

In [17]:
#aritmetic

In [18]:
contest_result = pd.Series(data=[10,5,100], index=["Atil","James","Lars"])

In [19]:
contest_result2 = pd.Series(data=[20,50,10], index=["Atil","James","Lars"])

In [20]:
contest_result

Atil      10
James      5
Lars     100
dtype: int64

In [21]:
contest_result2

Atil     20
James    50
Lars     10
dtype: int64

In [23]:
contest_result["Atil"]

np.int64(10)

In [26]:
contest_result2["James"]

np.int64(50)

In [27]:
final_result = contest_result + contest_result2 #indexler aynı olduğu için dataları sorunsuz bir şekilde toplayacak

In [28]:
final_result

Atil      30
James     55
Lars     110
dtype: int64

In [29]:
contest_result-contest_result2

Atil    -10
James   -45
Lars     90
dtype: int64

In [30]:
contest_result*contest_result2

Atil      200
James     250
Lars     1000
dtype: int64

In [31]:
contest_result/contest_result2

Atil      0.5
James     0.1
Lars     10.0
dtype: float64

In [34]:
different_series = pd.Series([20,30,40,50], ["a","b","c","d"])
different_series

a    20
b    30
c    40
d    50
dtype: int64

In [35]:
different_series2 = pd.Series([10,5,3,1], ["a","c","f","g"])
different_series2

a    10
c     5
f     3
g     1
dtype: int64

In [36]:
different_series + different_series2 #NaN - ortak olamayan indexler için

a    30.0
b     NaN
c    45.0
d     NaN
f     NaN
g     NaN
dtype: float64