In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
data = np.random.randn(4,3)

In [4]:
data

array([[ 0.14692148, -1.0378217 , -0.90431902],
       [ 1.35616977, -0.46148317,  0.15849841],
       [-1.19499254, -0.72373652, -1.19381467],
       [-0.98122861,  0.73900791, -0.99768335]])

In [5]:
#data_frame = pd.Series(data) #hata verecek çünkü series must be 1-dimensional

In [6]:
data_frame = pd.DataFrame(data)

In [7]:
data_frame

          0         1         2
0  0.146921 -1.037822 -0.904319
1  1.356170 -0.461483  0.158498
2 -1.194993 -0.723737 -1.193815
3 -0.981229  0.739008 -0.997683

In [8]:
type(data_frame)

pandas.core.frame.DataFrame

In [9]:
type(data_frame[0])

pandas.core.series.Series

In [10]:
data_frame[0]

0    0.146921
1    1.356170
2   -1.194993
3   -0.981229
Name: 0, dtype: float64

In [11]:
type(data_frame[0])

pandas.core.series.Series

In [12]:
new_df= pd.DataFrame(data, index = ["Atil", "Zeynep", "Atlas", "Mehmet"],columns=["Salary","Age","Seniority"])

In [13]:
new_df

          Salary       Age  Seniority
Atil    0.146921 -1.037822  -0.904319
Zeynep  1.356170 -0.461483   0.158498
Atlas  -1.194993 -0.723737  -1.193815
Mehmet -0.981229  0.739008  -0.997683

In [14]:
new_df["Age"]

Atil     -1.037822
Zeynep   -0.461483
Atlas    -0.723737
Mehmet    0.739008
Name: Age, dtype: float64

In [15]:
new_df["Salary"]

Atil      0.146921
Zeynep    1.356170
Atlas    -1.194993
Mehmet   -0.981229
Name: Salary, dtype: float64

In [16]:
new_df[["Age","Salary"]]

             Age    Salary
Atil   -1.037822  0.146921
Zeynep -0.461483  1.356170
Atlas  -0.723737 -1.194993
Mehmet  0.739008 -0.981229

In [17]:
#sadece row almak istersem

In [18]:
new_df.loc["Atil"] #atilin satırını getiirecek

Salary       0.146921
Age         -1.037822
Seniority   -0.904319
Name: Atil, dtype: float64

In [19]:
new_df.iloc[0] #atilin satırını getirir ama index aracılığıyla

Salary       0.146921
Age         -1.037822
Seniority   -0.904319
Name: Atil, dtype: float64

In [20]:
new_df

          Salary       Age  Seniority
Atil    0.146921 -1.037822  -0.904319
Zeynep  1.356170 -0.461483   0.158498
Atlas  -1.194993 -0.723737  -1.193815
Mehmet -0.981229  0.739008  -0.997683

In [21]:
new_df.iloc[:,2] #seniority=[2] kolonudaki (:) herşeyi getirecek

Atil     -0.904319
Zeynep    0.158498
Atlas    -1.193815
Mehmet   -0.997683
Name: Seniority, dtype: float64

In [22]:
new_df.iloc[1,2] #zeynep'in seniority

np.float64(0.15849840782320554)

# *DATA MANIPULATION (DATA MANİPÜLASYONU)*

In [23]:
new_df["Extra"]= 10 #hepsine 10 atayacak

In [24]:
new_df

          Salary       Age  Seniority  Extra
Atil    0.146921 -1.037822  -0.904319     10
Zeynep  1.356170 -0.461483   0.158498     10
Atlas  -1.194993 -0.723737  -1.193815     10
Mehmet -0.981229  0.739008  -0.997683     10

In [25]:
new_df.drop("Extra", axis=1) #drop "extra" removes that column with name extra , and the axis 1 means columns, axis 0 means row

          Salary       Age  Seniority
Atil    0.146921 -1.037822  -0.904319
Zeynep  1.356170 -0.461483   0.158498
Atlas  -1.194993 -0.723737  -1.193815
Mehmet -0.981229  0.739008  -0.997683

In [26]:
new_df # the extra column is not removed permanently

          Salary       Age  Seniority  Extra
Atil    0.146921 -1.037822  -0.904319     10
Zeynep  1.356170 -0.461483   0.158498     10
Atlas  -1.194993 -0.723737  -1.193815     10
Mehmet -0.981229  0.739008  -0.997683     10

In [27]:
new_df.drop("Extra", axis=1, inplace=True) #with inplace the removing is permanent

In [28]:
new_df

          Salary       Age  Seniority
Atil    0.146921 -1.037822  -0.904319
Zeynep  1.356170 -0.461483   0.158498
Atlas  -1.194993 -0.723737  -1.193815
Mehmet -0.981229  0.739008  -0.997683

In [29]:
new_df["Mehmet"] = 10

In [30]:
new_df

          Salary       Age  Seniority  Mehmet
Atil    0.146921 -1.037822  -0.904319      10
Zeynep  1.356170 -0.461483   0.158498      10
Atlas  -1.194993 -0.723737  -1.193815      10
Mehmet -0.981229  0.739008  -0.997683      10

In [31]:
new_df.drop("Mehmet") #row silecek çünkü axis belirtmedim ve default değeri sıfır yani row

          Salary       Age  Seniority  Mehmet
Atil    0.146921 -1.037822  -0.904319      10
Zeynep  1.356170 -0.461483   0.158498      10
Atlas  -1.194993 -0.723737  -1.193815      10

In [32]:
new_df.drop("Mehmet", axis=1, inplace=True) #column atacak

In [33]:
new_df

          Salary       Age  Seniority
Atil    0.146921 -1.037822  -0.904319
Zeynep  1.356170 -0.461483   0.158498
Atlas  -1.194993 -0.723737  -1.193815
Mehmet -0.981229  0.739008  -0.997683

In [34]:
new_df.drop("Mehmet", axis=0)

          Salary       Age  Seniority
Atil    0.146921 -1.037822  -0.904319
Zeynep  1.356170 -0.461483   0.158498
Atlas  -1.194993 -0.723737  -1.193815

In [35]:
new_df

          Salary       Age  Seniority
Atil    0.146921 -1.037822  -0.904319
Zeynep  1.356170 -0.461483   0.158498
Atlas  -1.194993 -0.723737  -1.193815
Mehmet -0.981229  0.739008  -0.997683

In [36]:
new_df.loc["Atlas"]

Salary      -1.194993
Age         -0.723737
Seniority   -1.193815
Name: Atlas, dtype: float64

In [37]:
new_df.loc["Atlas"]["Salary"]

np.float64(-1.1949925399040877)

In [38]:
new_df.loc["Atlas","Salary"] #same result diffwerent sytntax

np.float64(-1.1949925399040877)

In [39]:
new_df.loc["Atlas","Salary"] = 100 #yeniden tanımlayabilirm

In [40]:
new_df #atlasın maaşı 100 oldu

            Salary       Age  Seniority
Atil      0.146921 -1.037822  -0.904319
Zeynep    1.356170 -0.461483   0.158498
Atlas   100.000000 -0.723737  -1.193815
Mehmet   -0.981229  0.739008  -0.997683

In [41]:
new_df > 0

        Salary    Age  Seniority
Atil      True  False      False
Zeynep    True  False       True
Atlas     True  False      False
Mehmet   False   True      False

In [42]:
boolean_frame =new_df > 0
new_df[boolean_frame]

            Salary       Age  Seniority
Atil      0.146921       NaN        NaN
Zeynep    1.356170       NaN   0.158498
Atlas   100.000000       NaN        NaN
Mehmet         NaN  0.739008        NaN

In [43]:
new_df[new_df > 0]

            Salary       Age  Seniority
Atil      0.146921       NaN        NaN
Zeynep    1.356170       NaN   0.158498
Atlas   100.000000       NaN        NaN
Mehmet         NaN  0.739008        NaN

In [44]:
new_df

            Salary       Age  Seniority
Atil      0.146921 -1.037822  -0.904319
Zeynep    1.356170 -0.461483   0.158498
Atlas   100.000000 -0.723737  -1.193815
Mehmet   -0.981229  0.739008  -0.997683

In [45]:
new_df[new_df["Salary"]>1] #maaşı biden büyük olan sadece atlas var

           Salary       Age  Seniority
Zeynep    1.35617 -0.461483   0.158498
Atlas   100.00000 -0.723737  -1.193815

In [46]:
new_df[new_df["Age"]>0]

          Salary       Age  Seniority
Mehmet -0.981229  0.739008  -0.997683

# **DataFrame Index Mantığı**

In [47]:
new_df

            Salary       Age  Seniority
Atil      0.146921 -1.037822  -0.904319
Zeynep    1.356170 -0.461483   0.158498
Atlas   100.000000 -0.723737  -1.193815
Mehmet   -0.981229  0.739008  -0.997683

In [48]:
new_df.reset_index() #indexleri göserir ve ayrı kolon açar

    index      Salary       Age  Seniority
0    Atil    0.146921 -1.037822  -0.904319
1  Zeynep    1.356170 -0.461483   0.158498
2   Atlas  100.000000 -0.723737  -1.193815
3  Mehmet   -0.981229  0.739008  -0.997683

In [49]:
new_df #kalıcı bir değişiklik değil

            Salary       Age  Seniority
Atil      0.146921 -1.037822  -0.904319
Zeynep    1.356170 -0.461483   0.158498
Atlas   100.000000 -0.723737  -1.193815
Mehmet   -0.981229  0.739008  -0.997683

In [50]:
reset_frame = new_df.reset_index()

In [51]:
reset_frame

    index      Salary       Age  Seniority
0    Atil    0.146921 -1.037822  -0.904319
1  Zeynep    1.356170 -0.461483   0.158498
2   Atlas  100.000000 -0.723737  -1.193815
3  Mehmet   -0.981229  0.739008  -0.997683

In [52]:
#reset_frame.loc["Atil"] #error verecek çünkü artık index atıl değil

In [53]:
reset_frame.loc[0] #atılı verecek

index            Atil
Salary       0.146921
Age         -1.037822
Seniority   -0.904319
Name: 0, dtype: object

In [54]:
reset_frame.iloc[0] #yine aynı

index            Atil
Salary       0.146921
Age         -1.037822
Seniority   -0.904319
Name: 0, dtype: object

In [55]:
new_indices = ["Ati", "Zey", "Atl", "Meh"] #bu listeyi eklemek istiyorum

In [56]:
new_df["NewIndex"] = new_indices

In [57]:
new_df

            Salary       Age  Seniority NewIndex
Atil      0.146921 -1.037822  -0.904319      Ati
Zeynep    1.356170 -0.461483   0.158498      Zey
Atlas   100.000000 -0.723737  -1.193815      Atl
Mehmet   -0.981229  0.739008  -0.997683      Meh

In [58]:
new_df.set_index("NewIndex", inplace=True) #artık indexler NewIndex listesi

In [59]:
new_df

              Salary       Age  Seniority
NewIndex
Ati         0.146921 -1.037822  -0.904319
Zey         1.356170 -0.461483   0.158498
Atl       100.000000 -0.723737  -1.193815
Meh        -0.981229  0.739008  -0.997683

In [60]:
new_df.loc["Ati"]

Salary       0.146921
Age         -1.037822
Seniority   -0.904319
Name: Ati, dtype: float64

In [61]:
#MULTI INDEX

In [62]:
first_index = ["Simpson", "Simpson", "Simpson", "South Park", "South Park", "South Park"]

In [63]:
inner_index = ["Homer", "Bart", "Marge", "Cartman", "Kenny", "Kyle"]

In [64]:
zipped_index = list(zip(first_index, inner_index))

In [65]:
zipped_index

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [66]:
zipped_index = pd.MultiIndex.from_tuples(zipped_index)

In [67]:
zipped_index

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [68]:
sample_values = np.ones((6,2))

In [69]:
big_df = pd.DataFrame(sample_values, index=zipped_index, columns=["Salary", "Age"])

In [70]:
big_df

                    Salary  Age
Simpson    Homer       1.0  1.0
           Bart        1.0  1.0
           Marge       1.0  1.0
South Park Cartman     1.0  1.0
           Kenny       1.0  1.0
           Kyle        1.0  1.0

In [71]:
big_df["Age"]

Simpson     Homer      1.0
            Bart       1.0
            Marge      1.0
South Park  Cartman    1.0
            Kenny      1.0
            Kyle       1.0
Name: Age, dtype: float64

In [72]:
#big_df.loc["Homer"] # error verecek çünkü homera ulaşmam için ilk önce smpsona ulaşmam gerek

In [73]:
big_df.loc["Simpson"].loc["Homer"] #en dıştaki indexten en içe doğru.

Salary    1.0
Age       1.0
Name: Homer, dtype: float64